"""
URL ORM model.

NANOID RATIONALE:
- NanoID generates URL-safe random strings (A-Za-z0-9_-)
- 8-character NanoID → 64^8 = 281 trillion combinations
- At 1M URLs/day: collision probability after 1 billion records ≈ 0.000001%
  (birthday paradox: √(64^8) ≈ 16M IDs before 50% collision chance)
- WHY NOT Base62 sequential? Sequential IDs expose business metrics
  (competitor can see how many URLs you've generated by comparing IDs)
- WHY NOT UUID? UUID is 32 chars — too long for a short URL alias
- NanoID is cryptographically random, URL-safe, and compact

DUPLICATE LONG URL OPTIMIZATION:
- url_hash stores a SHA-256 of the long_url
- Indexed for fast duplicate detection: "has user already shortened this URL?"
- This avoids storing the same long_url twice for the same user

EXPIRATION:
- expires_at: NULL means "never expire"
- Application layer checks expiry on redirect; background job can clean up
- PostgreSQL partial indexes can efficiently query "active" URLs
"""

import uuid
from datetime import datetime

from sqlalchemy import (
    BigInteger,
    Boolean,
    DateTime,
    ForeignKey,
    Index,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class URL(Base):
    __tablename__ = "urls"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    slug: Mapped[str] = mapped_column(
        String(50),
        unique=True,
        nullable=False,
        index=True,  # Critical: redirect lookup is O(log n) via B-tree index
        comment="NanoID or user-supplied custom alias",
    )
    long_url: Mapped[str] = mapped_column(Text, nullable=False)
    url_hash: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        index=True,
        comment="SHA-256 of long_url for duplicate detection",
    )
    title: Mapped[str | None] = mapped_column(String(255), nullable=True)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    is_custom_alias: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False,
        comment="True if user supplied a custom slug",
    )
    click_count: Mapped[int] = mapped_column(
        BigInteger,
        default=0,
        nullable=False,
        comment="Denormalized counter for fast reads; source of truth is analytics table",
    )
    expires_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    # Foreign Keys
    owner_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Relationships
    owner: Mapped["User"] = relationship("User", back_populates="urls")  # noqa: F821
    analytics: Mapped[list["URLAnalytics"]] = relationship(  # noqa: F821
        "URLAnalytics", back_populates="url", lazy="select"
    )

    # Composite indexes for common query patterns
    __table_args__ = (
        Index("ix_urls_owner_active", "owner_id", "is_active"),
        Index("ix_urls_owner_hash", "owner_id", "url_hash"),  # Duplicate detection
    )

    def __repr__(self) -> str:
        return f"<URL slug={self.slug} long_url={self.long_url[:50]}>"
